language: cpp

compiler:
  - gcc
  - clang
  
os:
  - linux
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev/precise-backports  
  
before_script:  
  - mkdir build
  - cd build
  - cmake ..