# specify platforms
platform: 
  - Win32
  - x64  

# before everything
init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: dir C:\Libraries\boost

# set environment variables
environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\stage\lib
  
# clone directory
clone_folder: C:\projects\shark

# scripts to run before build
before_build:
  - cmd: cd C:\projects\shark
  - cmd: dir 
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 12
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 12 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBUILD_CORE_ONLY="%BUILD_CORE_ONLY%" -DDART_BUILD_EXAMPLES="%BUILD_EXAMPLES%" -DDART_BUILD_TUTORIALS="%BUILD_TUTORIALS%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" -Durdfdom_DIR="%urdfdom_DIR%" -Durdfdom_headers_DIR="%urdfdom_headers_DIR%" ..

# actual build process
build:
  project: C:\projects\shark\build\dart.sln # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
