# specify platforms
platform: 
#  - Win32
  - x64  

# configuration
configuration: Release

# set environment variables
environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\lib64-msvc-12.0
  OMP_NUM_THREADS: 2

# specify branch
branches:
  only:
    - appveyor
  
# before everything
init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: dir %BOOST_LIBRARYDIR%
  

# clone directory
clone_folder: C:\projects\shark

# scripts to run before build
before_build:
  - cmd: cd C:\projects\shark
  - cmd: dir 
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 12
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 12 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration%  -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"   ..
  - cmd: type C:\projects\shark\build\shark.sln 
  
# actual build process
build:
  project: C:\projects\shark\build\shark.sln 
  parallel: true                           
